spring:
  datasource:
    url: jdbc:mysql://uga-database.cfiymiwi4n93.ap-northeast-2.rds.amazonaws.com:3306/uga_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: olympus
    password: uga1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secretKey: rTUS9rPwE1BJWApUY6lhwZZOCdvM5blMzr6b1mRShLdbMn9eZNmXltdkP+AkLvArPlY44B2gwP0XQEp11+SZTA==
  refreshExp: 604800000 # 1week
  accessExp: 6000000 # 2hour

coolsms:
  api:
    key: NCSJ3ANB3A1EJWHA
    secret: KTTJHLB981ZWXLWQQMTIDZOKQ3EEX74G
    number: 01093677252

oauth:
  kakao:
    token-request-uri: "https://kauth.kakao.com/oauth/token" # 액세스 토큰 요청 URI
    member-info-request-uri: "https://kapi.kakao.com/v2/user/me" # 사용자 정보 요청 URI
    redirect-uri: "https://your.domain.com/oauth/kakao/callback" # Kakao Developers에 등록한 리다이렉트 URI
    client-id: "카카오 REST API 키 입력"

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui.html