spring:
  datasource:
    url: jdbc:postgresql://uga-db.cfiymiwi4n93.ap-northeast-2.rds.amazonaws.com:5432/uga_database
    driver-class-name: org.postgresql.Driver
    username: olympus
    password: uga1234567890
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: 10.0.0.83
#      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: ugafinal
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAXNGUVF4Z7FX6ZB6P
      secretKey: 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

jwt:
  secretKey: rTUS9rPwE1BJWApUY6lhwZZOCdvM5blMzr6b1mRShLdbMn9eZNmXltdkP+AkLvArPlY44B2gwP0XQEp11+SZTA==
  refreshExp: 604800000 # 1week
  accessExp: 6000000 # 2hour

coolsms:
  api:
    key: NCSJ3ANB3A1EJWHA
    secret: KTTJHLB981ZWXLWQQMTIDZOKQ3EEX74G
    number: 01093677252

oauth:
  kakao:
    client-id: 68638129f14ab8bd58b51039c4da7473
    client-secret: VGFGgmBTK4pLjIiBlTknkO4Qjx2K5vxN
    redirect-uri: https://uga.r-e.kr/oauth/kakao/login
  google:
    client-id: 622016426850-tj6617aaus6vts59hsncf7e58td66b4k.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: https://uga.r-e.kr/oauth/google/login

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui/index.html

  server:
    forward-headers-strategy: framework
    use-forward-headers: true