spring:
  datasource:
#    url: jdbc:mysql://bilidu-database.cx6wqaumgmz3.us-east-1.rds.amazonaws.com:3306/ducamiDatabase
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ducami_user
#    password: ducami1234!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui.html