spring:
  datasource:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secretKey: rTUS9rPwE1BJWApUY6lhwZZOCdvM5blMzr6b1mRShLdbMn9eZNmXltdkP+AkLvArPlY44B2gwP0XQEp11+SZTA==
  refreshExp: 604800000 # 1?
  accessExp: 6000000 # 2??

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    tags-sorter: alpha
    operationsSorter: alpha
    path: /swagger-ui.html